server.port=8081

spring.application.name=product-service
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.hibernate.show-sql= true

eureka.client.service-url.defaultZone= http://localhost:8761/eureka/
eureka.client.instance.prefer-ip-address= true